### PR TITLE
Voice support

### PR DESCRIPTION
**Pull request by Seniatical**
Begin to implement voice states and other voice related features into acord

### CODE REVIEW

**Comment by MrPotato374** [comment]
how's the progress? 👀

**Comment by Seniatical** [comment]
> how's the progress? 👀

Receiving data is done, working on sending + decoding received data.

**Comment by MrPotato374** [comment]
nice

**Comment by Seniatical** [comment]
Recent pushes has been focused on fixing issues such as #28

**Comment by Seniatical** [comment]
Update: Need to fix opus decoder and encoder and voice should be ready for ALPHA launch

**Comment by Seniatical** [comment]
**Receiving Data From Voice**
```py
from acord import BaseReciever

async with BaseReceiver(ws) as receiver:
    async for data in receiver:
         # Raw bytes from socket, needs decoding
         print(data)
```

**Comment by Seniatical** [comment]
Starting to write up `opus.py`, encoders decoders that stuff

**Comment by Seniatical** [comment]
Alpha of sending and receiving have been tested roughly, some bugs may be expected

**Pull request merged**
